### ISSUE TITLE
Type data for relations and entities in relation_type.npy and entity_type.npy

### ISSUE THREAD

**Issue by leiloong** [zhiweihu1103/QE-TEMP#1]
Dear authors, 
         Thx for your excellent work.
         I have a question about type preparation for relations and entities.
         In this paper, types for relations are derived from types of entities which entities are in the domain or range of these relations, like "compute the type information of r by taking the intersection of the types of the head and tail entities of
relation assertions in which r occurs".
<img width="382" alt="1660196295967" src="https://user-images.githubusercontent.com/9718821/184070553-fa7b7624-47e1-4788-b4ce-595d9adda6a8.png">
           However, the data in relation_type.npy and entity_type.npy shows that **union** of the types for each entity may be selected instead of "intersection of the types".
       For example, for triple (head, rel, tail) (0, 0, 1).
           In  entity_type.npy
           entity 0 has types [2252, 416, 3784, 2, 2320, 3773, 630, 3076, 843, 1343, 3677, 119, 3743, 893, 2239, 817, 3143, 3096, 657, 2765, 3778, 2634, 770, 2154, 3067, 1635, 3034, 1281, 2807, 747, 20, 3108, 3108, 1793, 2821, 2383, 3058, 730, 3551, 1319]
            entity 1 has types [1146, 2371, 1619, 1979, 770]
        while in relation_type.npy
           relation 0 has types [2, 2050, 5, 2056, 2058, 2059, 17, 20, 2068, 23, 2078, 32, 2081, 2082, 33, 2091, 2096, 59, 90, 2154, 2158, 115, 119, 2175, 2179, 2180, 135, 2192, 2198, 2199, 2204, 156, 157, 159, 169, 173, 2223, 183, 2239, 2240, 2243, 2245, 198, 202, 2252, 205, 2253, 224, 2273, 2276, 2277, 2278, 236, 2289, 249, 264, 2320, 276, 2338, 290, 294, 2350, 2364, 320, 2371, 2372, 326, 2375, 2383, 340, 343, 2406, 2409, 2411, 365, 2413, 2421, 2426, 385, 391, 393, 405, 2453, 407, 409, 411, 416, 2465, 2472, 431, 436, 2485, 2490, 446, 447, 452, 454, 460, 2515, 469, 471, 2521, 2529, 482, 485, 488, 2543, 496, 504, 515, 536, 2587, 540, 2589, 545, 2599, 2600, 557, 560, 563, 566, 2624, 2628, 583, 2634, 2637, 2638, 2643, 602, 605, 613, 2672, 630, 2691, 2694, 649, 652, 2704, 657, 2705, 2714, 684, 2733, 703, 713, 715, 2765, 719, 729, 730, 731, 739, 740, 2792, 747, 2802, 2807, 2809, 770, 2821, 776, 2827, 2833, 2834, 2851, 806, 2859, 817, 2873, 827, 2875, 842, 843, 2890, 845, 2894, 852, 858, 2907, 861, 2919, 2921, 873, 880, 883, 2932, 887, 2939, 893, 2947, 901, 2950, 904, 2964, 924, 934, 2984, 2986, 3012, 967, 971, 974, 977, 3025, 3027, 3034, 3035, 989, 3044, 996, 3058, 1012, 3065, 3067, 3068, 3069, 1023, 1024, 1026, 3075, 3076, 1030, 1031, 3085, 3096, 1058, 3108, 3109, 3111, 3113, 1067, 3126, 1080, 1084, 3137, 3139, 1094, 3143, 1096, 1097, 3151, 1114, 1117, 3169, 3178, 1134, 3189, 3190, 1143, 1146, 3206, 3211, 1168, 3220, 3228, 1181, 1180, 3236, 3237, 3238, 1196, 3250, 3256, 1208, 1211, 3265, 1223, 1235, 3291, 1244, 1245, 1247, 3298, 1266, 3318, 3325, 1280, 1281, 1282, 3339, 1303, 1306, 1309, 1319, 3380, 1335, 3386, 1343, 3401, 1363, 3418, 1375, 1376, 3433, 1390, 3439, 1397, 3449, 3453, 3456, 3461, 3474, 3483, 3489, 1442, 3490, 1470, 3525, 3527, 3531, 3533, 1495, 3545, 1497, 3551, 3553, 3558, 1520, 3572, 1530, 1532, 1542, 1551, 3600, 1560, 1570, 1572, 3649, 1604, 3656, 1615, 1616, 1619, 3677, 1629, 3679, 1635, 3684, 1641, 3700, 3703, 3706, 1667, 1671, 3730, 3735, 3738, 3739, 3743, 3750, 3754, 1707, 1710, 1718, 3773, 1725, 3776, 3778, 3779, 3784, 1737, 1743, 1750, 1770, 1777, 1780, 3838, 1793, 1794, 3845, 1799, 1802, 1805, 1809, 1820, 1845, 1868, 1880, 1885, 1889, 1896, 1898, 1899, 1919, 1921, 1925, 1929, 1956, 1964, 1965, 1979, 1992, 2029, 2035, 2044, 2045]
 
     Have you changed the "intersection of the types" to **union** of the types for each entity?
     Will you share the code and raw data to prepare the type data files (relation_type.npy and entity_type.npy)?

**Comment by zhiweihu1103** [comment]
Sorry, here is a typo in the article, we will fix it in the next version. The type information of the relationship is indeed the union of the type information of the head node and tail node related to the relationship.

Regarding the generation of entity_type.npy and relation_type.npy, entity_type can be directly created from the entity definition form in the original KG through rules. For relation_type, it is obtained on the basis of obtaining entity_type. Below I give the code generated by relation_type:

```python
import numpy as np
import os

def read_original_triple_data(file_path):
    triples = []
    with open(file_path, 'r') as handle:
        for line in handle.readlines():
            words = line.strip().split("\t")
            words = [int(w.strip()) for w in words]
            triples.append(words)
    return triples

def get_type_knowledge_graph(data_path):
    entity_type = np.load(data_path + '/entity_type.npy', allow_pickle=True)
    split_name_list = ['train.txt', 'valid.txt', 'test.txt']
    all_triples = []
    for split_name in split_name_list:
        all_triples.extend(read_original_triple_data(data_path + '/' + split_name))
    rel_type_dict = {}
    for single_triple in all_triples:
        head, rel, tail = single_triple[0], single_triple[1], single_triple[2]
        head_type = entity_type[head]
        tail_type = entity_type[tail]
        if rel not in rel_type_dict:
            rel_type_list = []
            rel_type_list.extend(set(head_type))
            rel_type_list.extend(set(tail_type))
            rel_type_set = set(rel_type_list)
            rel_type_dict[rel] = rel_type_set
        else:
            rel_type_list = list(rel_type_dict[rel])
            rel_type_list.extend(set(head_type))
            rel_type_list.extend(set(tail_type))
            rel_type_set = set(rel_type_list)
            rel_type_dict[rel] = rel_type_set

    rel_type_json = {}
    rel_type_list = []
    for key, value in rel_type_dict.items():
        rel_type_json[key] = list(value)
        rel_type_list.append(list(value))
    np.save(os.path.join(data_path, 'relation_type.npy'), rel_type_list)

if __name__ == "__main__":
    data_path = './data/only_test'
    get_type_knowledge_graph(data_path)
```
It should be noted that for the content of split_name_list, if it is a generalization test, it needs to be modified to ['train.txt']. But as represented by the parameter --neighbor_rel_type_samples in our code, this has little effect on the experimental results, since we are sampling the type information of the relation. Let me know if you have other questions.

**Comment by leiloong** [comment]
Got it. Thx a lot.
