### ISSUE TITLE
Inductive datasets based on FB15k-237-V2 and NELL995-V3

### ISSUE THREAD

**Issue by migalkin** [zhiweihu1103/QE-TEMP#2]
Hi guys, 

congratulations on the acceptance to IJCAI!

I was wondering if you have any plans to upload the new inductive query datasets (with EPFO queries) extracted from those GraIL graphs (I mean FB15k-237-V2 and NELL995-V3 here) on which you experimented in the paper?

**Comment by zhiweihu1103** [comment]
Sorry, I just saw. I have updated the dataset, see the following address: https://drive.google.com/drive/folders/15ZJo6zuoj0S3Sx_8nz7TKr3Tq7Ku8JMR

In addition, I have read many of your articles, such as StarE, NodePiece, GNN-QE, StarQ, etc. I hope to have the opportunity to exchange and cooperate.

**Comment by migalkin** [comment]
Got the datasets, thanks!

The paper mentions a graph of entity types (Type Graph) - I haven't found it in the dumps, but only `entity_type.npy` that contains a list of types for each node. So am I right that the Type Graph is not present explicitly?

**Comment by zhiweihu1103** [comment]
The type graph corresponds to ```relation_type.npy```.

**Comment by migalkin** [comment]
Could you please elaborate on its structure? (eg, in the README)
Checking for instance the NELL-V3 graph, `relation_type.npy` has 284 lists, the graph has 284 relations and 267 types. The paper (p.4) says:
>  a novel type graph with types as nodes and relations as edges

so what are the nodes and edges in `relation_type.npy`?

**Comment by zhiweihu1103** [comment]
let me explain, each entry in ```relation_type.npy``` corresponds to a relation, and the relation id is consistent with ```id2rel.pkl```. For each relation, there is a list, and the id in the list corresponds to the type corresponding to the current relation. So, using these relations and types, we can build a type graph.

**Comment by zhiweihu1103** [comment]
The ```relation_type.npy``` is from ```entity_type.npy```, as I said in issue #1.

**Comment by migalkin** [comment]
Thanks! I think I got the gist of its content
