### ISSUE TITLE
Identify the type of a entity or relation

### ISSUE THREAD

**Issue by lazyloafer** [zhiweihu1103/QE-TEMP#4]
Hi, Hu:
I‘m interested in the type-aware embeddings in your paper. I wonder how to identify these types? (after all, the datasets provided in your link are labeled with types, but the datasets in BetaE's source codes are not labeled with entity and relationship types)

**Comment by zhiweihu1103** [comment]
Type knowledge is introduced as external knowledge. For the type of entity, the original dataset is included, but it is not used in papers such as BetaE. For the type knowledge of relation, it is completed by constructing a type graph based on the type knowledge of the entity.
