### ISSUE TITLE
can't find the file 'stats.txt'.

### ISSUE THREAD

**Issue by yw3l** [zhiweihu1103/QE-TEMP#6]
Dear @zhiweihu1103 ,
    Thanks for your excellent work. I am not sure whether bother you now is a right chance or not . when I ran the main function in the  'main.py',which reminds me `FileNotFoundError: [Errno 2] No such file or directory: './data/FB15k-237-long_chain/stats.txt'`,
I don't know this file is supplied in the program or need to generate it. 
the error happened in  the next code: 
`with open('%s/stats.txt'%args.data_path) as f:`
`    entrel = f.readlines()`
`    nentity = int(entrel[0].split(' ')[-1])`
`    nrelation = int(entrel[1].split(' ')[-1])`
`    ntype = int(entrel[2].split(' ')[-1])`

sincerely, yours.

**Comment by zhiweihu1103** [comment]
You need to change the file path to the data set we provide. For example, you need to change the ./data/FB15k-237-long_chain path to: ./data/FB15k-237-betae. We have provided the specific data set here:https://drive.google.com/drive/folders/15ZJo6zuoj0S3Sx_8nz7TKr3Tq7Ku8JMR
